/// Bundled affirmation library (~120). Used for first install and v4 migration.
abstract final class SeedAffirmations {
  static const entries = <(String category, String content)>[
    // Calm (20)
    ('calm', 'My words can shape a kinder day.'),
    ('calm', 'I welcome gentle progress.'),
    ('calm', 'I grow at my own pace.'),
    ('calm', 'I release what I cannot control.'),
    ('calm', 'I speak to myself with kindness.'),
    ('calm', 'I breathe in calm and breathe out tension.'),
    ('calm', 'I give time and space to my soul to restore.'),
    ('calm', 'Peace begins with a single conscious breath.'),
    ('calm', 'I am safe in this moment.'),
    ('calm', 'My nervous system knows how to settle.'),
    ('calm', 'I let go of urgency and choose presence.'),
    ('calm', 'Stillness is a strength I cultivate daily.'),
    ('calm', 'I trust myself to handle what comes.'),
    ('calm', 'Every exhale carries away what no longer serves me.'),
    ('calm', 'I am allowed to rest without earning it.'),
    ('calm', 'Calm is always available inside me.'),
    ('calm', 'I soften my shoulders and unclench my jaw.'),
    ('calm', 'I choose peace over perfection.'),
    ('calm', 'My mind can be quiet and that is enough.'),
    ('calm', 'I return to center with compassion.'),

    // Bold (20)
    ('bold', 'I choose thoughts that help me feel steady, loved, and capable.'),
    ('bold', 'I am rooted, steady, and strong.'),
    ('bold', 'Today I make room for what matters.'),
    ('bold', 'I am powerful, focused, and ready.'),
    ('bold', 'I was born to be successful.'),
    ('bold', 'I take up space unapologetically.'),
    ('bold', 'My voice deserves to be heard.'),
    ('bold', 'I act with courage even when I feel afraid.'),
    ('bold', 'I am proud of myself for getting this far.'),
    ('bold', 'I turn obstacles into opportunities.'),
    ('bold', 'I trust my ability to figure things out.'),
    ('bold', 'I am becoming the person I admire.'),
    ('bold', 'I show up boldly for my dreams.'),
    ('bold', 'My potential expands every single day.'),
    ('bold', 'I am resilient, resourceful, and ready.'),
    ('bold', 'I claim my power with grace.'),
    ('bold', 'Nothing can dim the light that I am.'),
    ('bold', 'I lead my life with intention.'),
    ('bold', 'I am capable of more than I know.'),
    ('bold', 'Today I choose brave action.'),

    // Manifest (20)
    ('manifest', 'What I speak, I create.'),
    ('manifest', 'My dreams are becoming my reality.'),
    ('manifest', 'I am aligned with my highest path.'),
    ('manifest', 'I trust the timing of my life.'),
    ('manifest', 'I am becoming more confident every day.'),
    ('manifest', 'Everything I need is already on its way to me.'),
    ('manifest', 'I visualize my goals and take aligned steps.'),
    ('manifest', 'The universe supports my intentions.'),
    ('manifest', 'I am a magnet for miracles.'),
    ('manifest', 'My future self is proud of choices I make today.'),
    ('manifest', 'I speak my desires in present tense.'),
    ('manifest', 'I am open to unexpected blessings.'),
    ('manifest', 'My mindset creates my reality.'),
    ('manifest', 'I claim abundance with gratitude.'),
    ('manifest', 'I am worthy of every dream I hold.'),
    ('manifest', 'What is meant for me will not miss me.'),
    ('manifest', 'I release doubt and embrace faith.'),
    ('manifest', 'I am co-creating a beautiful life.'),
    ('manifest', 'My intentions are clear and powerful.'),
    ('manifest', 'I trust that things will work out how they need to.'),

    // Abundance (20)
    ('abundance', 'Abundance flows to me with ease.'),
    ('abundance', 'I am open to receiving more good.'),
    ('abundance', 'Prosperity is my natural state.'),
    ('abundance', 'Money comes to me in expected and unexpected ways.'),
    ('abundance', 'I deserve financial freedom and security.'),
    ('abundance', 'I am grateful for the wealth already in my life.'),
    ('abundance', 'I attract opportunities that increase my income.'),
    ('abundance', 'My value is reflected in what I receive.'),
    ('abundance', 'I release scarcity thinking with love.'),
    ('abundance', 'Wealth expands when I share generously.'),
    ('abundance', 'I am a channel for prosperity.'),
    ('abundance', 'Every day I grow more financially confident.'),
    ('abundance', 'I welcome abundance in all forms.'),
    ('abundance', 'My resources multiply as I use them wisely.'),
    ('abundance', 'I am worthy of luxury and comfort.'),
    ('abundance', 'Good fortune finds me effortlessly.'),
    ('abundance', 'I invest in myself and my future.'),
    ('abundance', 'Abundance is my birthright.'),
    ('abundance', 'I celebrate others success and attract my own.'),
    ('abundance', 'More than enough is always available to me.'),

    // Love (20)
    ('love', 'I love and accept myself fully.'),
    ('love', 'I give and receive love freely.'),
    ('love', 'I am worthy of deep, genuine love.'),
    ('love', 'I am loved.'),
    ('love', 'I LOVE MYSELF.'),
    ('love', 'I treat myself the way I wish to be treated.'),
    ('love', 'My heart is open and protected.'),
    ('love', 'I forgive myself and move forward with love.'),
    ('love', 'I attract relationships that nourish me.'),
    ('love', 'I am enough exactly as I am.'),
    ('love', 'Self-love is the foundation of everything I build.'),
    ('love', 'I honor my needs without guilt.'),
    ('love', 'I radiate warmth and kindness.'),
    ('love', 'My body deserves my appreciation.'),
    ('love', 'I choose myself every day.'),
    ('love', 'Love grows wherever I focus gratitude.'),
    ('love', 'I am gentle with my imperfections.'),
    ('love', 'I deserve compassion from myself.'),
    ('love', 'My inner child feels safe with me.'),
    ('love', 'I am surrounded by love I cannot always see.'),

    // Focus (20)
    ('focus', 'My mind is clear and my focus is sharp.'),
    ('focus', 'I show up fully for what matters.'),
    ('focus', 'Deep work flows when I stay present.'),
    ('focus', 'One task at a time brings my best results.'),
    ('focus', 'I protect my attention like a precious resource.'),
    ('focus', 'Distractions pass; my purpose remains.'),
    ('focus', 'I finish what I start with discipline and ease.'),
    ('focus', 'Clarity comes when I simplify.'),
    ('focus', 'I am fully engaged in this moment.'),
    ('focus', 'My goals have my undivided attention today.'),
    ('focus', 'I work with intention, not urgency.'),
    ('focus', 'Focus is a gift I give myself daily.'),
    ('focus', 'I prioritize progress over perfection.'),
    ('focus', 'My energy follows my focus.'),
    ('focus', 'I create space for deep thinking.'),
    ('focus', 'I am disciplined, not deprived.'),
    ('focus', 'Every focused hour moves me forward.'),
    ('focus', 'I trust my ability to concentrate.'),
    ('focus', 'I eliminate noise and choose signal.'),
    ('focus', 'Present-moment awareness is my superpower.'),
  ];
}
